.inputs {
	display: flex;
	gap: 1em;
	width: 100%;
	justify-content: center;
	align-items: center;
	font-size: .8em;
}

.inputs>h4 {
	padding: 0;
	margin: 0;
}

.inputs>input {
	width: fit-content;
	font-size: 1em;
}