.subtitle {
	margin: 2em 0 .5em 0;
}

.inputs {
	display: flex;
	gap: 1em;
	width: 100%;
	justify-content: center;
	align-items: center;
	font-size: .8em;
}

.inputs>h4 {
	padding: 0;
	margin: 0;
}

.inputs>input {
	width: fit-content;
	font-size: 1em;
}

.add-word-contain {
	width: 100%;
	max-width: 400px;
	padding: 1em;
	display: grid;
	gap: 0;
	grid-template-columns: 4fr 1fr;
	border: 1px dashed var(--black);
	border-radius: var(--radius);
}

.add-word-contain>input {
	background-color: var(--white);
	color: var(--black);
	border: 1px solid var(--black);
	border-radius: var(--radius) 0 0 var(--radius);
}

.add-word-contain>button {
	border-radius: 0 var(--radius) var(--radius) 0;
	font-size: 1em;
}

.add-word-contain>button:hover {
	transform: none;
}

.add-word-contain>ul {
	text-transform: uppercase;
	margin: 0;
	margin-top: 1em;
}

.add-word-contain>ul>li {
	width: 100%;
	display: flex;
	align-items: center;
	gap: 1em;
}

.add-word-contain>ul>li>h4 {
	margin: 0;
}